/**
 * /field/heat copy for it, bg, et, fi, lt, lv, hu.
 */

import type { Lang } from "../i18n";
import type { HeatCopy } from "./heatFieldI18n";

const HEAT_FIELD_OBSERVED_AT = "2026-06-28T14:30:00Z";
const HEAT_TEMP_C = 39;

const POINT_IDS = ["hydrant_pulawska", "biblio_mokotow", "metro_kurtyna"] as const;

function fopLine(): string {
  return `FOP/0.1 @${HEAT_FIELD_OBSERVED_AT} | temp=${HEAT_TEMP_C}.0 | src=CHANNEL_A_CITIZEN | deploy=warszawa-mokotow-heat-2026`;
}

export const HEAT_FIELD_EXTRA: Partial<Record<Lang, HeatCopy>> = {
  it: {
    statusLine: "VARSAVIA · 28 GIUGNO 2026 · 16:30",
    factTemp: "39°C",
    factSubtitle: "ondata di caldo estremo",
    alertRcbLabel: "Allerta RCB",
    alertRcbBody:
      "Allerta caldo estremo dal 28 giugno. Evitate il sole 11–17. Bevete acqua, cercate locali freschi. Malessere — 112.",
    transportTitle: "Trasporti",
    transportTram: "Tram su Puławska rallentati — rischio deformazione rotaie",
    transportSkm: "Vagoni SKM oltre 44°C",
    transportMore: "→ altro",
    waterSaveTitle: "Come risparmiare acqua?",
    waterSaveQuestion: "Vi serve davvero un terzo scarico oggi, o basta uno?",
    ctaNearbyHelp: "📍 Trova acqua e ombra",
    ctaVoiceReport: "🎤 Registra un'osservazione",
    voiceStart: "Inizia registrazione",
    voiceRecording: "Registrazione…",
    voiceStop: "Termina",
    voiceSaved: "✓ Registrazione salvata",
    voiceReviewPrompt: "È tutto corretto?",
    voicePlay: "Riascolta",
    voiceSend: "Invia",
    voiceOrType: "oppure scrivi",
    voiceTranscribePlaceholder: "Opzionale: correggi la trascrizione…",
    voiceSentTitle: "✓ Segnalazione ricevuta",
    voiceSentBody: "Grazie. Potete tornare alla realtà.",
    ctaAnotherObservation: "Lascia un'altra osservazione",
    voiceUnsupported: "Registrazione non disponibile — scrivi sotto.",
    voiceMicDenied: "Microfono bloccato — scrivi sotto.",
    layer2Title: "Nelle vicinanze",
    distanceM: "{n} m",
    distanceWalk: "{n} min a piedi",
    pointLabels: {
      hydrant_pulawska: {
        name: "Idrante-fontana (Puławska/Odyńca)",
        action: "Prendi acqua",
        statusOk: "Funziona",
        statusFail: "Non disponibile",
        kindLabel: "Acqua",
      },
      biblio_mokotow: {
        name: "Riparo climatizzato (Biblioteca Mokotów)",
        action: "Entra",
        statusOk: "Aperto",
        statusFail: "Chiuso",
        kindLabel: "Ombra",
      },
      metro_kurtyna: {
        name: "Cortina d'acqua (metro Pole Mokotowskie)",
        action: "Verifica",
        statusOk: "Funziona",
        statusFail: "Guasto elettrico",
        kindLabel: "Acqua · ombra",
      },
    },
    traceTitle: "Traccia (EVENT → TRACE)",
    layer3Title: "Rolloutowo · artifacts",
    fopLine: fopLine(),
    knowledgeLink: "Piano di adattamento climatico di Varsavia al 2030",
    paperLink: "Szulczewska et al. — superficie biologicamente attiva a Varsavia",
    back: "← Indietro",
    technicalData: "Dati tecnici",
    whyContext: "Perché lo mostriamo",
    sourcesTitle: "Fonti",
    researchTitle: "Ricerca",
    hypothesisTitle: "Ipotesi",
    hypothesisHeat:
      "Il caldo estremo aumenta la domanda di acqua e ombra nello spazio pubblico (provvisorio).",
    devEventCodes: "Codici evento (dev): SELECT(POMOC_W_POBLIZU), …",
    moreContextLabel: "Altro contesto",
  },
  bg: {
    statusLine: "ВАРШАВА · 28 ЮНИ 2026 · 16:30",
    factTemp: "39°C",
    factSubtitle: "екстремна топлинна вълна",
    alertRcbLabel: "RCB сигнал",
    alertRcbBody:
      "Предупреждение за екстремна жега от 28 юни. Избягвайте слънце 11–17. Пийте вода. Лошо самочувствие — 112.",
    transportTitle: "Транспорт",
    transportTram: "Трамваи на Puławska забавят — риск от изкривяване",
    transportSkm: "Вагони SKM над 44°C",
    transportMore: "→ още",
    waterSaveTitle: "Как да пестим вода?",
    waterSaveQuestion: "Наистина ли ви трябва трето изплакване днес?",
    ctaNearbyHelp: "📍 Вода и сянка наблизо",
    ctaVoiceReport: "🎤 Запишете наблюдение",
    voiceStart: "Започни запис",
    voiceRecording: "Запис…",
    voiceStop: "Спри",
    voiceSaved: "✓ Записът е запазен",
    voiceReviewPrompt: "Всичко наред ли е?",
    voicePlay: "Пусни",
    voiceSend: "Изпрати",
    voiceOrType: "или напишете",
    voiceTranscribePlaceholder: "По избор: коригирайте текста…",
    voiceSentTitle: "✓ Сигналът е получен",
    voiceSentBody: "Благодарим. Можете да се върнете към реалността.",
    ctaAnotherObservation: "Оставете друго наблюдение",
    voiceUnsupported: "Записът не е наличен — напишете по-долу.",
    voiceMicDenied: "Няма достъп до микрофона — напишете по-долу.",
    layer2Title: "Наблизо",
    distanceM: "{n} m",
    distanceWalk: "{n} мин пеша",
    pointLabels: {
      hydrant_pulawska: {
        name: "Хидран (Puławska/Odyńca)",
        action: "Вода",
        statusOk: "Работи",
        statusFail: "Недостъпен",
        kindLabel: "Вода",
      },
      biblio_mokotow: {
        name: "Климатизирано убежище (Biblioteka Mokotów)",
        action: "Влез",
        statusOk: "Отворено",
        statusFail: "Затворено",
        kindLabel: "Сянка",
      },
      metro_kurtyna: {
        name: "Водна завеса (метро Pole Mokotowskie)",
        action: "Провери",
        statusOk: "Работи",
        statusFail: "Повреда на захранването",
        kindLabel: "Вода · сянка",
      },
    },
    traceTitle: "Следа (EVENT → TRACE)",
    layer3Title: "Rolloutowo · artifacts",
    fopLine: fopLine(),
    knowledgeLink: "План за адаптация на Варшава до 2030",
    paperLink: "Szulczewska et al. — биологично активна площ",
    back: "← Назад",
    technicalData: "Технически данни",
    whyContext: "Защо показваме това",
    sourcesTitle: "Източници",
    researchTitle: "Изследвания",
    hypothesisTitle: "Хипотеза",
    hypothesisHeat: "Екстремната жега увеличава нуждата от вода и сянка (provisional).",
    devEventCodes: "Кодове (dev): SELECT(POMOC_W_POBLIZU), …",
    moreContextLabel: "Повече контекст",
  },
  et: {
    statusLine: "VARSSAVI · 28. JUUNI 2026 · 16:30",
    factTemp: "39°C",
    factSubtitle: "äärmuslik kuumalaine",
    alertRcbLabel: "RCB hoiatus",
    alertRcbBody:
      "Äärmusliku kuumuse hoiatus alates 28. juunist. Vältige päikest 11–17. Joo vett. Halb enesetunne — 112.",
    transportTitle: "Transport",
    transportTram: "Trammid Puławskal aeglustuvad",
    transportSkm: "SKM vagunites üle 44°C",
    transportMore: "→ rohkem",
    waterSaveTitle: "Kuidas vett säästa?",
    waterSaveQuestion: "Kas teil on täna tõesti vaja kolmandat loputust?",
    ctaNearbyHelp: "📍 Vesi ja varju",
    ctaVoiceReport: "🎤 Salvesta vaatlus",
    voiceStart: "Alusta salvestamist",
    voiceRecording: "Salvestamine…",
    voiceStop: "Lõpeta",
    voiceSaved: "✓ Salvestis salvestatud",
    voiceReviewPrompt: "Kas kõik on õige?",
    voicePlay: "Kuula",
    voiceSend: "Saada",
    voiceOrType: "või kirjuta",
    voiceTranscribePlaceholder: "Valikuline: paranda transkriptsiooni…",
    voiceSentTitle: "✓ Teade vastu võetud",
    voiceSentBody: "Aitäh. Võite naasta reaalsusesse.",
    ctaAnotherObservation: "Jäta uus vaatlus",
    voiceUnsupported: "Salvestamine pole saadaval — kirjuta allpool.",
    voiceMicDenied: "Mikrofon on blokeeritud — kirjuta allpool.",
    layer2Title: "Lähedal",
    distanceM: "{n} m",
    distanceWalk: "{n} min jalgsi",
    pointLabels: {
      hydrant_pulawska: {
        name: "Hüdrant (Puławska/Odyńca)",
        action: "Vesi",
        statusOk: "Töötab",
        statusFail: "Pole saadaval",
        kindLabel: "Vesi",
      },
      biblio_mokotow: {
        name: "Jahutatud varjupaik (Mokotów raamatukogu)",
        action: "Sisene",
        statusOk: "Avatud",
        statusFail: "Suletud",
        kindLabel: "Vari",
      },
      metro_kurtyna: {
        name: "Veekardin (metro)",
        action: "Kontrolli",
        statusOk: "Töötab",
        statusFail: "Toite rike",
        kindLabel: "Vesi · vari",
      },
    },
    traceTitle: "Jälje (EVENT → TRACE)",
    layer3Title: "Rolloutowo · artifacts",
    fopLine: fopLine(),
    knowledgeLink: "Varssavi kliimakohanemiskava 2030",
    paperLink: "Szulczewska et al. — bioloogiliselt aktiivne pind",
    back: "← Tagasi",
    technicalData: "Tehnilised andmed",
    whyContext: "Miks me seda näitame",
    sourcesTitle: "Allikad",
    researchTitle: "Uuringud",
    hypothesisTitle: "Hüpotees",
    hypothesisHeat: "Äärmuslik kuumus suurendab vajadust vee ja varju järele (provisional).",
    devEventCodes: "Sündmuskoodid (dev): SELECT(POMOC_W_POBLIZU), …",
    moreContextLabel: "Rohkem konteksti",
  },
  fi: {
    statusLine: "VARSOVA · 28. KESÄKUUTA 2026 · 16:30",
    factTemp: "39°C",
    factSubtitle: "äärimmäinen helleaalto",
    alertRcbLabel: "RCB-varoitus",
    alertRcbBody:
      "Hellevaroitus 28.6. alkaen. Vältä aurinkoa klo 11–17. Juo vettä. Huonovointisuus — 112.",
    transportTitle: "Liikenne",
    transportTram: "Raitiovaunut Puławskalla hidastuvat",
    transportSkm: "SKM-vaunuissa yli 44°C",
    transportMore: "→ lisää",
    waterSaveTitle: "Miten säästää vettä?",
    waterSaveQuestion: "Tarvitsetko tänään kolmannen huuhtelun?",
    ctaNearbyHelp: "📍 Vesi ja varjo",
    ctaVoiceReport: "🎤 Tallenna havainto",
    voiceStart: "Aloita tallennus",
    voiceRecording: "Tallennus…",
    voiceStop: "Lopeta",
    voiceSaved: "✓ Tallenne tallennettu",
    voiceReviewPrompt: "Onko kaikki oikein?",
    voicePlay: "Toista",
    voiceSend: "Lähetä",
    voiceOrType: "tai kirjoita",
    voiceTranscribePlaceholder: "Valinnainen: korjaa litterointi…",
    voiceSentTitle: "✓ Ilmoitus vastaanotettu",
    voiceSentBody: "Kiitos. Voit palata todellisuuteen.",
    ctaAnotherObservation: "Jätä toinen havainto",
    voiceUnsupported: "Tallennus ei käytettävissä — kirjoita alle.",
    voiceMicDenied: "Mikrofoni estetty — kirjoita alle.",
    layer2Title: "Lähellä",
    distanceM: "{n} m",
    distanceWalk: "{n} min kävellen",
    pointLabels: {
      hydrant_pulawska: {
        name: "Hydrootti (Puławska/Odyńca)",
        action: "Hae vettä",
        statusOk: "Toimii",
        statusFail: "Ei saatavilla",
        kindLabel: "Vesi",
      },
      biblio_mokotow: {
        name: "Viileä suoja (Mokotówin kirjasto)",
        action: "Mene sisään",
        statusOk: "Avoinna",
        statusFail: "Suljettu",
        kindLabel: "Varjo",
      },
      metro_kurtyna: {
        name: " Vesiverho (metro)",
        action: "Tarkista",
        statusOk: "Toimii",
        statusFail: "Sähkövika",
        kindLabel: "Vesi · varjo",
      },
    },
    traceTitle: "Jälki (EVENT → TRACE)",
    layer3Title: "Rolloutowo · artifacts",
    fopLine: fopLine(),
    knowledgeLink: "Varsovan ilmastonmuutossopeutumissuunnitelma 2030",
    paperLink: "Szulczewska et al. — biologisesti aktiivinen pinta",
    back: "← Takaisin",
    technicalData: "Tekniset tiedot",
    whyContext: "Miksi näytämme tämän",
    sourcesTitle: "Lähteet",
    researchTitle: "Tutkimus",
    hypothesisTitle: "Hypoteesi",
    hypothesisHeat: "Äärimmäinen helle lisää veden ja varjon tarvetta (provisional).",
    devEventCodes: "Tapahtumakoodit (dev): SELECT(POMOC_W_POBLIZU), …",
    moreContextLabel: "Lisää kontekstia",
  },
  lt: {
    statusLine: "VARŠUVA · 2026-06-28 · 16:30",
    factTemp: "39°C",
    factSubtitle: "ekstremali karščio banga",
    alertRcbLabel: "RCB perspėjimas",
    alertRcbBody:
      "Ekstremalaus karščio perspėjimas nuo birželio 28 d. Venkite saulės 11–17. Gerkite vandenį. Bloga savijauta — 112.",
    transportTitle: "Transportas",
    transportTram: "Tramvajai Puławskoje lėtėja",
    transportSkm: "SKM vagonuose virš 44°C",
    transportMore: "→ daugiau",
    waterSaveTitle: "Kaip taupyti vandenį?",
    waterSaveQuestion: "Ar tikrai reikia trečio nuleidimo?",
    ctaNearbyHelp: "📍 Vanduo ir pavėsis",
    ctaVoiceReport: "🎤 Įrašykite stebėjimą",
    voiceStart: "Pradėti įrašymą",
    voiceRecording: "Įrašoma…",
    voiceStop: "Baigti",
    voiceSaved: "✓ Įrašas išsaugotas",
    voiceReviewPrompt: "Ar viskas teisinga?",
    voicePlay: "Klausyti",
    voiceSend: "Siųsti",
    voiceOrType: "arba rašykite",
    voiceTranscribePlaceholder: "Neprivaloma: pataisykite transkripciją…",
    voiceSentTitle: "✓ Pranešimas gautas",
    voiceSentBody: "Ačiū. Galite grįžti į realybę.",
    ctaAnotherObservation: "Palikti kitą stebėjimą",
    voiceUnsupported: "Įrašymas nepasiekiamas — rašykite žemiau.",
    voiceMicDenied: "Mikrofonas užblokuotas — rašykite žemiau.",
    layer2Title: "Šalia",
    distanceM: "{n} m",
    distanceWalk: "{n} min pėsčiomis",
    pointLabels: {
      hydrant_pulawska: {
        name: "Hidrantas (Puławska/Odyńca)",
        action: "Vanduo",
        statusOk: "Veikia",
        statusFail: "Nepasiekiama",
        kindLabel: "Vanduo",
      },
      biblio_mokotow: {
        name: "Vėsinama prieglauda (Mokotów biblioteka)",
        action: "Įeiti",
        statusOk: "Atidaryta",
        statusFail: "Uždaryta",
        kindLabel: "Šešėlis",
      },
      metro_kurtyna: {
        name: "Vandens užuolaida (metro)",
        action: "Patikrinti",
        statusOk: "Veikia",
        statusFail: "Maitinimo gedimas",
        kindLabel: "Vanduo · šešėlis",
      },
    },
    traceTitle: "Pėdsakas (EVENT → TRACE)",
    layer3Title: "Rolloutowo · artifacts",
    fopLine: fopLine(),
    knowledgeLink: "Varšuvos prisitaikymo planas iki 2030",
    paperLink: "Szulczewska et al. — biologiškai aktyvus plotas",
    back: "← Atgal",
    technicalData: "Techniniai duomenys",
    whyContext: "Kodėl tai rodoma",
    sourcesTitle: "Šaltiniai",
    researchTitle: "Tyrimai",
    hypothesisTitle: "Hipotezė",
    hypothesisHeat: "Ekstremalus karštis didina vandens ir šešėlio poreikį (provisional).",
    devEventCodes: "Įvykių kodai (dev): SELECT(POMOC_W_POBLIZU), …",
    moreContextLabel: "Daugiau konteksto",
  },
  lv: {
    statusLine: "VARŠAVA · 2026. G. 28. JŪNIJS · 16:30",
    factTemp: "39°C",
    factSubtitle: "ekstremāla karstuma vilnis",
    alertRcbLabel: "RCB brīdinājums",
    alertRcbBody:
      "Ekstremāla karstuma brīdinājums no 28. jūnija. Izvairieties no saules 11–17. Dzeriet ūdeni. Slikta pašsajūta — 112.",
    transportTitle: "Transports",
    transportTram: "Tramvaji Puławskā palēninās",
    transportSkm: "SKM vagonos virs 44°C",
    transportMore: "→ vairāk",
    waterSaveTitle: "Kā taupīt ūdeni?",
    waterSaveQuestion: "Vai tiešām vajag trešo noskalošanu?",
    ctaNearbyHelp: "📍 Ūdens un ēna",
    ctaVoiceReport: "🎤 Ierakstiet novērojumu",
    voiceStart: "Sākt ierakstu",
    voiceRecording: "Ieraksta…",
    voiceStop: "Beigt",
    voiceSaved: "✓ Ieraksts saglabāts",
    voiceReviewPrompt: "Vai viss pareizi?",
    voicePlay: "Klausīties",
    voiceSend: "Sūtīt",
    voiceOrType: "vai rakstiet",
    voiceTranscribePlaceholder: "Pēc izvēles: labojiet transkripciju…",
    voiceSentTitle: "✓ Ziņojums saņemts",
    voiceSentBody: "Paldies. Varat atgriezties realitātē.",
    ctaAnotherObservation: "Atstāt vēl vienu novērojumu",
    voiceUnsupported: "Ieraksts nav pieejams — rakstiet zemāk.",
    voiceMicDenied: "Mikrofons bloķēts — rakstiet zemāk.",
    layer2Title: "Tuvumā",
    distanceM: "{n} m",
    distanceWalk: "{n} min kājām",
    pointLabels: {
      hydrant_pulawska: {
        name: "Hidrants (Puławska/Odyńca)",
        action: "Ūdens",
        statusOk: "Darbojas",
        statusFail: "Nav pieejams",
        kindLabel: "Ūdens",
      },
      biblio_mokotow: {
        name: "Dzesināta patversme (Mokotów bibliotēka)",
        action: "Ieiet",
        statusOk: "Atvērts",
        statusFail: "Slēgts",
        kindLabel: "Ēna",
      },
      metro_kurtyna: {
        name: "Ūdens aizkars (metro)",
        action: "Pārbaudīt",
        statusOk: "Darbojas",
        statusFail: "Barošanas kļūme",
        kindLabel: "Ūdens · ēna",
      },
    },
    traceTitle: "Pēda (EVENT → TRACE)",
    layer3Title: "Rolloutowo · artifacts",
    fopLine: fopLine(),
    knowledgeLink: "Varšavas adaptācijas plāns līdz 2030",
    paperLink: "Szulczewska et al. — bioloģiski aktīvā platība",
    back: "← Atpakaļ",
    technicalData: "Tehniskie dati",
    whyContext: "Kāpēc mēs to rādām",
    sourcesTitle: "Avoti",
    researchTitle: "Pētījumi",
    hypothesisTitle: "Hipotēze",
    hypothesisHeat: "Ekstremāls karstums palielina ūdens un ēnas vajadzību (provisional).",
    devEventCodes: "Notikumu kodi (dev): SELECT(POMOC_W_POBLIZU), …",
    moreContextLabel: "Vairāk konteksta",
  },
  hu: {
    statusLine: "VARSÓ · 2026. JÚNIUS 28. · 16:30",
    factTemp: "39°C",
    factSubtitle: "extrém hőhullám",
    alertRcbLabel: "RCB riasztás",
    alertRcbBody:
      "Extrém hőriadó június 28-tól. Kerülje a napot 11–17 között. Igyon vizet. Rossullét — 112.",
    transportTitle: "Közlekedés",
    transportTram: "A Puławskai villamosok lassítanak",
    transportSkm: "SKM kocsikban 44°C felett",
    transportMore: "→ több",
    waterSaveTitle: "Hogyan spóroljunk vizet?",
    waterSaveQuestion: "Tényleg kell ma a harmadik öblítés?",
    ctaNearbyHelp: "📍 Víz és árnyék",
    ctaVoiceReport: "🎤 Rögzítsen megfigyelést",
    voiceStart: "Felvétel indítása",
    voiceRecording: "Felvétel…",
    voiceStop: "Leállítás",
    voiceSaved: "✓ Felvétel mentve",
    voiceReviewPrompt: "Minden rendben?",
    voicePlay: "Lejátszás",
    voiceSend: "Küldés",
    voiceOrType: "vagy írjon",
    voiceTranscribePlaceholder: "Opcionális: javítsa az átiratot…",
    voiceSentTitle: "✓ Bejelentés fogadva",
    voiceSentBody: "Köszönjük. Visszatérhet a valóságba.",
    ctaAnotherObservation: "Új megfigyelés",
    voiceUnsupported: "A felvétel nem elérhető — írjon alább.",
    voiceMicDenied: "Nincs mikrofon-hozzáférés — írjon alább.",
    layer2Title: "A közelben",
    distanceM: "{n} m",
    distanceWalk: "{n} perc gyalog",
    pointLabels: {
      hydrant_pulawska: {
        name: "Tűzcsap (Puławska/Odyńca)",
        action: "Víz",
        statusOk: "Működik",
        statusFail: "Nem elérhető",
        kindLabel: "Víz",
      },
      biblio_mokotow: {
        name: "Hűvös menedék (Mokotów könyvtár)",
        action: "Belépés",
        statusOk: "Nyitva",
        statusFail: "Zárva",
        kindLabel: "Árnyék",
      },
      metro_kurtyna: {
        name: "Vízfüggöny (metró)",
        action: "Ellenőriz",
        statusOk: "Működik",
        statusFail: "Áramkimaradás",
        kindLabel: "Víz · árnyék",
      },
    },
    traceTitle: "Nyom (EVENT → TRACE)",
    layer3Title: "Rolloutowo · artifacts",
    fopLine: fopLine(),
    knowledgeLink: "Varsó klímaadaptációs terv 2030-ig",
    paperLink: "Szulczewska et al. — biológiailag aktív felület",
    back: "← Vissza",
    technicalData: "Műszaki adatok",
    whyContext: "Miért mutatjuk",
    sourcesTitle: "Források",
    researchTitle: "Kutatás",
    hypothesisTitle: "Hipotézis",
    hypothesisHeat: "Az extrém hőség növeli a víz és árnyék iránti igényt (provisional).",
    devEventCodes: "Eseménykódok (dev): SELECT(POMOC_W_POBLIZU), …",
    moreContextLabel: "Több kontextus",
  },
};

// Ensure point label keys stay aligned with HEAT_POINTS
for (const lang of Object.keys(HEAT_FIELD_EXTRA) as Lang[]) {
  const block = HEAT_FIELD_EXTRA[lang]!;
  for (const id of POINT_IDS) {
    if (!block.pointLabels[id]) {
      throw new Error(`heat field ${lang} missing point label ${id}`);
    }
  }
}
