export type Lang = "pl" | "en" | "it";

export const copy = {
  pl: {
    title: "WARSZAWASZA",
    subtitle: "Miasto jest żywe. Styl jest komunikatem.",
    manifesto: "Warszawa nie jest produktem. Warszawa jest stanem.",
    hud: "Ray-Ban HUD // Urban Signal",
    trueFalse: "Cytrusowy Kursar: TRUE / FALSE",
    trueLine: "TRUE: Miasto mówi przez znaki, rytm i ludzi.",
    falseLine: "FALSE: Strona nie jest sklepem. Jest wejściem do opowieści.",
    fieldLabel: "FIELD PHASE",
    fieldPhase: "RECOVERY",
    fieldNote: "Silnik sygnału miejskiego: dropy, mapy, momenty.",
    cards: [
      { title: "FIRA", text: "Zauważ. Zrozum. Pomóż." },
      { title: "NORKA", text: "Zabezpiecz pamięć. Schowaj sygnał." },
      { title: "KOT", text: "Patrz zanim zareagujesz." },
      { title: "ORZEŁ", text: "Wznieś sygnał ponad szum." },
    ],
    reveal: "Ujawnij sygnały terenowe",
    revealing: "Skanowanie pola…",
    dropsTitle: "Drop 001 — tożsamość w języku",
    dropsEmpty: "Pole ciche. Uruchom skan, aby odczytać dropy.",
    studio: "Wejście do studia",
    footer: "Moja. Twoja. Wasza. Warszawa.",
  },
  en: {
    title: "WARSZAWASZA",
    subtitle: "The city is alive. Style is a signal.",
    manifesto: "Warsaw is not a product. Warsaw is a state.",
    hud: "Ray-Ban HUD // Urban Signal",
    trueFalse: "Citrus Cursor: TRUE / FALSE",
    trueLine: "TRUE: The city speaks through signs, rhythm and people.",
    falseLine: "FALSE: This is not a shop. It is an entrance to a story.",
    fieldLabel: "FIELD PHASE",
    fieldPhase: "RECOVERY",
    fieldNote: "Urban signal engine: drops, maps, moments.",
    cards: [
      { title: "FIRA", text: "Notice. Understand. Help." },
      { title: "NORKA", text: "Secure memory. Hide the signal." },
      { title: "KOT", text: "Look before you react." },
      { title: "ORZEŁ", text: "Raise the signal above the noise." },
    ],
    reveal: "Reveal field signals",
    revealing: "Scanning field…",
    dropsTitle: "Drop 001 — identity in language",
    dropsEmpty: "Field silent. Run scan to read drops.",
    studio: "Studio entrance",
    footer: "Mine. Yours. Ours. Warsaw.",
  },
  it: {
    title: "WARSZAWASZA",
    subtitle: "La città è viva. Lo stile è un segnale.",
    manifesto: "Varsavia non è un prodotto. Varsavia è uno stato.",
    hud: "Ray-Ban HUD // Urban Signal",
    trueFalse: "Cursore Agrumato: TRUE / FALSE",
    trueLine: "TRUE: La città parla attraverso segni, ritmo e persone.",
    falseLine: "FALSE: Non è un negozio. È un ingresso in una storia.",
    fieldLabel: "FIELD PHASE",
    fieldPhase: "RECOVERY",
    fieldNote: "Motore del segnale urbano: drop, mappe, momenti.",
    cards: [
      { title: "FIRA", text: "Nota. Comprendi. Aiuta." },
      { title: "NORKA", text: "Proteggi la memoria. Nascondi il segnale." },
      { title: "KOT", text: "Guarda prima di reagire." },
      { title: "ORZEŁ", text: "Alza il segnale sopra il rumore." },
    ],
    reveal: "Rivela segnali di campo",
    revealing: "Scansione del campo…",
    dropsTitle: "Drop 001 — identità nel linguaggio",
    dropsEmpty: "Campo silenzioso. Avvia scansione per leggere i drop.",
    studio: "Ingresso studio",
    footer: "Mia. Tua. Nostra. Varsavia.",
  },
} as const;

export type Copy = (typeof copy)[Lang];
